export const BLOCKS = [
  {type: 'group'},
  {type: 'row'},
  {type: 'heroImage'},
  {type: 'title'},
  {type: 'paragraph'},
  {type: 'img'},
  {type: 'button'},
  {type: 'card'},
  {type: 'socialLinks'},
  {type: 'ensembles'},
  {type: 'schedule'},
  {type: 'gallery'},
  {type: 'contactForm'},
]
